### ISSUE TITLE
Support symfony/framework-bundle ^3.0

### ISSUE THREAD

**Issue by yakobe** [igorw/IgorwFileServeBundle#19]
At the moment this bundle has several deprecated that are incompatible with 3.x.

@igorw : Is/should this repository still maintained or is it suggested to use an alternative? If it should still be maintained, would you like a PR to make it compatible (eg use request stack etc?).

**Comment by fkrauthan** [comment]
@yakobe Have you found a good alternative for this bundle? I was thinking of upgrading one of my projects to symfony3 and right now this bundle is sort of a blocker.

**Comment by yakobe** [comment]
Unfortunately not. It also seems like this is nolonger maintained. Have you encountered any alternatives? Perhaps we should create a fork?

**Comment by toverux** [comment]
There is no direct alternative, but the Symfony's built-in [BinaryFileResponse](https://github.com/symfony/http-foundation/blob/master/BinaryFileResponse.php) is quite similar, with `X-Accel-Redirect` support and PHP streams fallback.
