### ISSUE TITLE
Given filename not set in safari

### ISSUE THREAD

**Issue by ghost** [igorw/IgorwFileServeBundle#4]
Safari does not use the filename set from the options. E.G. if i use:

`$options = array( 'serve_filename' => 'my_file.pdf', 'inline' => false );`

As the options, it downloads the file as the route name (in my case "new"). In firefox it works.

**Comment by inmarelibero** [comment]
I'm experimenting the same issue, did someone find any solution/workaround?

**Comment by inmarelibero** [comment]
with

```
$response->headers->set(
    'Content-Disposition',
    $disposition . "; filename=\"".($this->options['serve_filename']."\"")
);
```

it works fine, but it would be a modification just for safari

**Comment by inmarelibero** [comment]
maybe it could be useful, to fix this, to pass the $request object to the `igorw_file_serve.response_factory` and trig if user-agent if `safari` or anything else

**Comment by igorw** [comment]
Looking into this.

**Comment by igorw** [comment]
The problem is that most browsers are not RFC compliant. For IE, safari and konqueror we need:

```
"filename=" . rawurlencode($file)
```

For all others we can use the correct:

```
"filename*=UTF-8''" . rawurlencode($file)
```

**Comment by inmarelibero** [comment]
yes, that's exactly the problem. I see two solutions:

1) (deprecated) add an option to `create()` function, letting the user overwrite manually the `Content-Disposition` if needed

2) pass the Symfony Request object as argument to the service; so in

```
protected function setResponseHeaders(Response $response)
```

add an `if` on the user agent coming from the $request object and then setting the "right" `Content-Disposition`

anyway both are not the best..

**Comment by igorw** [comment]
I have pushed an update, please let me know what you think and if it works for you.

**Comment by inmarelibero** [comment]
cool, it's working perfectly for me

**Comment by igorw** [comment]
Great, I'll close this then. Thanks!
