### ISSUE TITLE
large files (> 100Mb) download problem

### ISSUE THREAD

**Issue by inmarelibero** [igorw/IgorwFileServeBundle#9]
I'm experiencing a weird problem: with a website deployed to a remote server, when I try to download a file via IgorwFileServerBundle which dimension is > 100Mb (more or less), it fails.

more infos:
- the file is a .zip (but experienced with other types)
- it downloads a file with the correct filename
- the downloaded file size is 0 (the file is empty)

anyone experienced something similar?

**Comment by igorw** [comment]
Which web server is it running? And is it using FPM? Which driver are you using? Do you get any PHP errors in the logs?

**Comment by inmarelibero** [comment]
webserver is Apache 2.2.22, it's a normal virtual server, no special configuration/extensions

I'm not using FPM

oh, I didn't check the logs.. they give a useful information:

```
[error] PHP   1. {main}() [...]/web/app.php:0, referer: [...]
[error] PHP   2. Symfony\\Component\\HttpFoundation\\Response->send() [...]app.php:12, referer: [...]
[error] PHP   3. Igorw\\FileServeBundle\\Response\\PhpResponse->sendContent() [...]/app/cache/prod/classes.php:3036, referer: [...]
[error] PHP   4. readfile() [...]/vendor/bundles/Igorw/FileServeBundle/Response/PhpResponse.php:18, referer: [...]
[error] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 128151553 bytes) in [...]/vendor/bundles/Igorw/FileServeBundle/Response/PhpResponse.php on line 18, referer: [...]
```

it is possible that apache is trying to put in ram the entire file and goes out of memory?

I had the idea to use http://ca2.php.net/manual/en/function.readfile.php#48683

**Comment by inmarelibero** [comment]
and it's working now! I changed PhpResponse.php as follows:

```
public function sendContent()
{
    return $this->readfile_chunked($this->filename);
}

private function readfile_chunked ($filename) {
    $chunksize = 1*(1024*1024); // how many bytes per chunk
    $buffer = '';
    $handle = fopen($filename, 'rb');
    if ($handle === false) {
        return false;
    }
    while (!feof($handle)) {
        $buffer = fread($handle, $chunksize);
        print $buffer;
    }
    return fclose($handle);
}
```

following http://ca2.php.net/manual/en/function.readfile.php#48683

**Comment by igorw** [comment]
Hmm, this might be due to output buffering. Can you try this instead?

```
$file = fopen($filename, 'rb');
$out = fopen('php://output', 'wb');

stream_copy_to_stream($file, $out, $this->maxlen, $this->offset);

fclose($out);
fclose($file);
```

**Comment by inmarelibero** [comment]
yes, it seems actually working this too.

but I don't understand `$this->maxlen` and `$this->offset`. I tried simply with

```
public function sendContent()
{
    $file = fopen($this->filename, 'rb');
    $out = fopen('php://output', 'wb');

    stream_copy_to_stream($file, $out);

    fclose($out);
    fclose($file);
}
```

If I use `$this->maxlen` and `$this->offset`, shouldn't I do anyway a `for` cicle?

**Comment by igorw** [comment]
Oh sorry, I mistakenly copy-pasted that from [this symfony PR](https://github.com/symfony/symfony/pull/4546) and forgot to remove, or mention the PR.

**Comment by igorw** [comment]
I will change this to `stream_copy_to_stream` and hope nothing breaks.

EDIT: I mean _pray_ nothing breaks.

**Comment by igorw** [comment]
@inmarelibero @kbond can you confirm this is working before I tag another release?

**Comment by inmarelibero** [comment]
+1, for me it's working perfectly

**Comment by igorw** [comment]
... and tagged v1.0.2. Cheers!

**Comment by kbond** [comment]
awesome, looking at that symfony PR, will the functionality of this bundle be available in core as of 2.2?

**Comment by inmarelibero** [comment]
@igorw cool! thanks ;)
@kbond yes from what I understand it will be another type of response, and it's made very very well

**Comment by igorw** [comment]
Yep, the plan is to ship this functionality in core with 2.2.

**Comment by inmarelibero** [comment]
@igorw talking about [the Symfony PR](https://github.com/symfony/symfony/pull/4546) you reported before, do you think that communicating the problem we faced in [this commit](https://github.com/igorw/IgorwFileServeBundle/commit/2b5010abceb04d2326eee9d9270cdafd2df8e907#Response/AbstractResponseFactory.php) would be useful?

it was the one about the weird behavior in some browsers about the filename, finally we adopted

```
if (!$userAgent || preg_match('#MSIE|Safari|Konqueror#', $userAgent)) {
    return "filename=".rawurlencode($filename);
}

return "filename*=UTF-8''".rawurlencode($filename);
```

in [Symfony/Component/HttpFoundation/BinaryFileResponse.php](https://github.com/niklasf/symfony/blob/2f7bbbfec15222097d4632bf05344d9f4d09a198/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php) I cannot see anything about that.

**Comment by igorw** [comment]
Looks like they have a better solution which did in fact ship with 2.1: [ResponseHeaderBag::makeDisposition()](https://github.com/symfony/symfony/blob/2.1/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L214).

We should use that instead, I've created a ticket: #11.
